apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "priorauth-engine.fullname" . }}
  labels:
    {{- include "priorauth-engine.labels" . | nindent 4 }}
data:
  PA_HTTP_ADDR: ":{{ .Values.service.targetPort }}"
  PA_VERSION: {{ default .Chart.AppVersion .Values.image.tag | quote }}
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
